// <auto-generated/>
using System.Net;
using Monitor.Common;

public class Program
{
    static void Main(string[] args)
    {

        if (args.Length == 0 || string.IsNullOrEmpty(args[0]))
        {
            throw new ArgumentException("Invalid arguments passed.", "Arguments passed in should equal 2 and should be the ON Uri and the OFF Uri");
        }
        else
        {
            if (args.Length != 2)
            {
                throw new ArgumentException("Invalid arguments passed.", "Arguments passed in should equal 2 and should be the ON Uri and the OFF Uri");
            }
            else
            {
                string OnUri = args[0];
                string OffUri = args[1];

                if (!Uri.IsWellFormedUriString(OnUri, UriKind.Absolute))
                {
                    throw new WebException($"Invalid Uri passed - {OnUri}");
                }

                if (!Uri.IsWellFormedUriString(OffUri, UriKind.Absolute))
                {
                    throw new WebException($"Invalid Uri passed - {OffUri}");
                }

                IWebCam webCam = new WebCam();
                webCam.OnUri = OnUri;
                webCam.OffUri = OffUri;

                while (webCam.WebCamServiceWrapperAsync().Result != 1)
                {
                    Thread.Sleep(1000);
                }
            }
        }
    }
}